### ISSUE TITLE
breaking changes in material-ui/next

### ISSUE THREAD

**Issue by karmajunkie** [TarikHuber/material-ui-responsive-drawer#2]
I'm running into a few warnings about unknown props, which are coming from changes in material-ui's components. I'm happy to track them down and make the necessary changes, but given that it will probably break compatibility with material-ui <1.0.0-alpha, how would you like to see a PR on it?

**Comment by TarikHuber** [comment]
What do you think that we make a extra branch for the '@next' we could release as alpha on npm?That way we should just follow MUI alpha as it changes. I think the @next will have more breaking changes so we should take care that this repo is up to date with them. What do you think about that?

**Comment by karmajunkie** [comment]
Agreed, sounds great to me.

**Comment by TarikHuber** [comment]
Next branch created.
There where lots of changes to do to make it work with the @next. Glad we used a new branch. It won't work for both because lots of Commponends changed name, props and behavior.

Here is a demo of the @next: https://material-ui-responsive-drawer.firebaseapp.com/

There is still some work to do with the `Drawer` but the erros should be gone.

I hope the package is available with the @next tag to install. Never published beta packages so not sure if I did it right.

**Comment by karmajunkie** [comment]
I didn't actually expect it to work, but installing `material-ui-responsive-drawer@next` did actually work, though I suspect trying to roll another build will get confused without the incremental version number. 

It might be better to build an alpha version, e.g. `2.0.0-alpha.0` in keeping with semver. What do you think?

**Comment by TarikHuber** [comment]
Yes. Greate idea. Will make it tonight. Glad that it worked :) Thinking now to also move my project to the @next
If you need more components you can check it out: https://github.com/TarikHuber/react-most-wanted
I will update it also to the @next branch.

**Comment by TarikHuber** [comment]
Released npm version 2.0.0-alpha.0 that supports material-ui@next
Closing issue.
