### ISSUE TITLE
toggling drawer immediately toggles it closed

### ISSUE THREAD

**Issue by karmajunkie** [TarikHuber/material-ui-responsive-drawer#3]
I'm not sure where the actual issue here is, whether its with material-ui/next or with the way its being used here, but the issue can be demonstrated in the demo app. If the drawer is set with docking to false, and the drawer is toggled open, the backdrop immediately has its `handleBackdropClick` handler triggered, which in turn triggers `onRequestClose`. 

If the Drawer is set to docked mode, the issue goes away but there's also no way to close the drawer without adding a button to do that explicitly, which is suboptimal. What's kind of weird is that the backdrop, which is added as a result of the initial click of the menu button, is receiving a click event at all—it makes me wonder if its got something to do with the path through redux.

**Comment by TarikHuber** [comment]
There is the possible usage:
- disable docked
- open drawer
- now you are stuck and can't close it if there is no explicit control for that

It is suboptimal but this possible usage comes from MUI. You are responsible to composite your UI so that the user can't get to this situation. That's the reason why in the demo there is a explicit button. In most user-cases there should be a menu that closes the drawer on menu click. 

I don't think that we should remove the action that allows the developer to disable `docked` just because he could make this mistake. Maybe someone needs the Drawer docked disabled but opened so he can close it only with the controls he provide to the user. 

> With great power comes great responsibility ;)

All that behavior comes form MUI itself. the only thing this package does is to change the props: docked, open, onRequestClose. All other props set to `ResposniveDrawer` are directly send to the `Drawer` component of MUI. This makes it very easy to maintain because you can change everything else with the `ResponsiveDrawer` like you could with the normal `Drawer`. We don't have to explicitly add more features to this project, for example, to give the user the possibility to change the style or width etc... all those are just dropped down to the real MUI Drawer.

I'm closing this issue because it is related to features of the MUI Drawer and not the `ResponsiveDrawer`.

**Comment by karmajunkie** [comment]
For the sake of completeness, and in case anyone else comes looking for a solution, what I ended up doing was debouncing the toggle within a time window by handling both the AppBar's `onLeftIconButtonTouchTap`  and the drawer's `handleRequestClose` and throwing away the request if it comes within a small time window.  This allows the responsive drawer to maintain its overlay and keeps the user experience good. My implementation looks like this (note that I'm using custom breakpoints):

```
class AppContainer extends Component {
  constructor(props){
    super(props);
    this.state = {
      lastClick: 0
    }
  }

  appBarClick = () => {
    this.setState({lastClick: Date.now()});
    this.props.toggleDrawerOpen();
  }

  toggleSiteNavOpen = () => {
    let deltaT=Date.now() - this.state.lastClick;
    if(this.state.lastClick && (deltaT > 200)){
      this.props.toggleDrawerOpen();
    }
  }

  render(){
    let {children} = this.props;
    return (
        <MuiThemeProvider>
        <div id='app-container' className='row'>
        <ResponsiveDrawer breackPoint="md" onRequestClose={this.toggleSiteNavOpen}>
          <SiteNav open={this.state.siteNavOpen} onHandleDrawerRequestClose={this.onHandleDrawerRequestClose} />
        </ResponsiveDrawer>
        <BodyContainer width={256} breackPoint='md'>
          <ResponsiveAppBar style={appBarStyles} onLeftIconButtonTouchTap={this.appBarClick} toggleDrawerOpen={this.toggleSiteNavOpen} width={256} breackPoint='md' />
          <div>
            {children}
          </div>
        </BodyContainer>
        </div>
        </MuiThemeProvider> );
  }

}

```
